export default function aboutPage() {
  return (
    <div className='about_container'>
      <h2>About</h2>
      <p>Hi I&apos;m Kelly!</p>
      <p>
        I&apos;m a software developer with a passion for building scalable and
        efficient systems. I have a strong background in full-stack development,
        specializing in TypeScript, React and Node.js. I enjoy tackling complex
        problems and finding innovative solutions. In my free time I love
        exploring new technologies and contributing to open-source projects. I
        believe in the power of collaboration and continuous learning, and
        I&apos;m always looking for new challenges to grow my skills.
      </p>
      <p>
        The above is a generic blurb generated by AI, and while I do generally
        agree with it, I think it misses a few key points. As is often the case
        with AI, we&apos;re hitting the broad strokes without neccessarily
        getting to the details.
      </p>
      <p>
        A key aspect it fails to capture is the essence of why I actually enjoy
        software engineering. Sure, I love the process of building things, the
        creativity involved in problem-solving and bringing ideas to life, but
        what I enjoy most is doing this with others. I love working with people,
        collaborating on a project, mentoring others, or simply sharing in the
        process or sharing our knowledge and experiences. The human aspect of
        software engineering is so much more rewarding than doing the same code
        with a computer.
      </p>
      <p>
        In this age of AI, I think it&apos;s important to remember that software
        engineering is not just about writing code or building systems,
        it&apos;s about understanding people, their needs, how technology can
        enhance our lives, and all the very human considerations that come with
        it.
      </p>
      <p>
        Having said that, I am absolutely a software developer with a passion
        for building scalable and efficient systems who is looking for new
        challenges and opportunities to grow my skills, so if you&apos;re
        looking for a dev who is passionate about building good things with
        great people, hit me up!
      </p>
      <p></p>

      <div>
        <h3>Where To Find Me:</h3>
        <p>
          LinkedIn:{' '}
          <a
            href='https://www.linkedin.com/in/kelly-keating-nz'
            target='_blank'
            className='link-pop'
          >
            kelly-keating-nz
          </a>
        </p>
        <p>
          GitHub:{' '}
          <a
            href='https://github.com/kelly-keating'
            target='_blank'
            className='link-pop'
          >
            kelly-keating
          </a>
        </p>
        {/* TODO: contact form? email is a no */}
      </div>

      <div>
        {/* TODO: add experience */}
        <h3>Previous Roles</h3>
        <p>To be added...</p>
      </div>
    </div>
  )
}
